[package]
name = "xrcf"
description = "xr compiler framework"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
anyhow = "1.0.86"

[dev-dependencies]
indoc = "2"
